spring.application.name=gateway-service
server.port=8080

# Backend services
gateway.auth-service-url=http://localhost:8082
gateway.course-service-url=http://localhost:8083
gateway.registration-service-url=http://localhost:8084

# JWT (phai giong voi auth-service)
jwt.secret=MySecretKeyForJwtTokenGenerationMustBeAtLeast256BitsLong!!

# Partner API Key
gateway.partner-api-key=crs-partner-key-2026

# Tat Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
